# 파이썬 3월 14일 강의 복습
> "6월 25일 "

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최석진
- categories: [Python]

## 리스트 - 선언, 연산, 컨테이너형 객체, 가변객체, 메소드, 중첩리스트, 리스트 컴프리헨션
- june 25 ,2022

### list

선언

`-`  리스트의 선언

In [2]:
a=[11,22]
a

[11, 22]

In [3]:
type(a)

list

`-` 비어있는 리스트 선언

In [5]:
a=[] # 방법 1
a

[]

In [9]:
a=list() #방법 2
a

[]

연산

`-` 더하기 연산

In [12]:
a=[11,12]
b=[12,13]

In [13]:
a+b

[11, 12, 12, 13]

- 리스트에서 더하기 연산은 더하기 개념이 아니라 원소 추가의 개념

`-` 빼기 연산 (정의되지 않음)

In [14]:
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

`-` 곱하기 연산 

In [15]:
a*2

[11, 12, 11, 12]

- 리스트에서 곱하기 연산은 원소의 반복의 개념

`-`  나눗셈 연산 (정의되지 않음)

In [17]:
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-`  더하기와 곱하기는 원소의 추가와 반복추가를 의미하지만 그렇다고 해서 뺄셈과 나눗셈이 원소의 삭제를 의미하지는 않음

`-` 더하기와 곱하기로 산술적인 `+`,`*` 을 계산하고 싶은경우에는 ??? 

(예제)

In [18]:
a=[1,2]
b=[3,4]

(풀이1)

In [20]:
a[0]+b[0] #a믜 첫번째 원소를 추출 , b의 첫번째 원소를 추출, 둘을 더함 (추출한 원소는 int형이므로 연산 가능!)

4

In [21]:
a[1]+b[1] #a믜 두번째 원소를 추출 , b의 두번째 원소를 추출, 둘을 더함 (추출한 원소는 int형이므로 연산 가능!)

6

(풀이2)

numpy 패키지 사용 (파이썬의 여러 수치연산들을 담당하는 라이브러리)

패키지 설치 방법
- `!pip install numpy`#최신버전의 패키지를 설치
- `!conda install -c conda-forge numpy -y` #안전한 버전의 패키지를 설치

설치된 패키지 사용 방법
- `import numpy` 한뒤에 `numpy.??` 로 기능을 사용
- `import numpy as np` 한뒤에 `np.??` 로 기능을 사용

In [31]:
import numpy as np #numpy를 불러오는데 np라는 이름으로 불러오겠다

In [24]:
a=[1,2]
b=[3,4]

In [26]:
aa=np.array(a)
bb=np.array(b)
# aa,bb는 리스트가 아니라 numpy array
# numpy.array()는 numpy패키지에서 제공하는 array함수를 쓰겠다는 의미!
# numpy -> 상위개념 , array() -> 하위개념

In [27]:
aa+bb

array([4, 6])

In [29]:
2*aa

array([2, 4])

In [30]:
2*aa+1

array([3, 5])

인덱싱

`-` str형과 동일한 방식

In [32]:
a=[11,22,33,44,55]
a[-1:]

[55]

### list 고급

컨테이너형 객체, 가변객체

`-` list의 원소는 int, float 등만 가능한 것이 아니다. (리스트는 컨테이너형 객체 이므로)

In [33]:
lst=[1,3.14,True,'a',[1,2],(1,2),{'name':'iu','age':27},{1,2,3}]

In [34]:
lst

[1, 3.14, True, 'a', [1, 2], (1, 2), {'name': 'iu', 'age': 27}, {1, 2, 3}]

In [35]:
type(lst[0]),type(lst[1]),type(lst[2]),type(lst[3]),type(lst[4]),type(lst[5]),type(lst[6]),type(lst[7])

(int, float, bool, str, list, tuple, dict, set)

`-` str은 컨테이너형이 아니다. 
- str의 모든원소는 문자임

In [36]:
'abcd'[2]

'c'

`-` 리스트의 원소는 수정할 수 있다. (리스트는 가변객체)

In [38]:
a=[11,22,33]
a

[11, 22, 33]

In [39]:
a[0]=111

In [40]:
a

[111, 22, 33]

(원소수정 가능)

In [42]:
a=['s','e','o','k','j','i','n']
a

['s', 'e', 'o', 'k', 'j', 'i', 'n']

In [43]:
a[0]='S'

In [44]:
a

['S', 'e', 'o', 'k', 'j', 'i', 'n']

(원소수정 불가능)

In [45]:
a='seokjin'
a

'seokjin'

In [46]:
a[0]

's'

In [47]:
a[0]='S'

TypeError: 'str' object does not support item assignment

`-` 리스트 원소 삭제

(예제)

문자로 된 리스트 선언 방법1

In [48]:
a=['s','e','o','k','j','i','n']
a

['s', 'e', 'o', 'k', 'j', 'i', 'n']

문자로 된 리스트 선언 방법2

In [50]:
a='seokjin' #string으로 된 a를 선언
a=list(a)   #list(a)를 통해 str을 list로 변환 -> 그 결과를 다시 a에 저장
a

['s', 'e', 'o', 'k', 'j', 'i', 'n']

첫번째 원소를 삭제하고 싶다면?

In [51]:
del a[0]

In [52]:
a

['e', 'o', 'k', 'j', 'i', 'n']

이상태에서 다시 첫번째 원소를 삭제하면?

In [55]:
del a[0]
a

['o', 'k', 'j', 'i', 'n']

`-` 리스트의 원소 추가

(예제) 비어있는 리스트를 만들고 원소 0,1,2를 차례로 추가

(풀이1)

In [56]:
a=[]
a

[]

In [57]:
a=a+[0]
a

[0]

In [58]:
a=a+[1]
a

[0, 1]

In [59]:
a=a+[2]
a

[0, 1, 2]

(풀이2)

In [60]:
a=[]
a

[]

In [61]:
a+=[0]
a

[0]

In [62]:
a+=[1]
a

[0, 1]

In [63]:
a+=[2]
a

[0, 1, 2]

(풀이3) 리스트 특화기능(=메소드)를 이용

In [64]:
a=[]
a

[]

In [65]:
a.append(0)
a

[0]

In [66]:
a.append(1)
a

[0, 1]

In [67]:
a.append(2)
a

[0, 1, 2]

- `a+[4]` 와 `a.append(4)`의 차이점?

In [68]:
a=[1,2,3]
a+[4]

[1, 2, 3, 4]

In [69]:
a ##a의 연산결과는 그대로. 변화 없음

[1, 2, 3]

In [71]:
a=[1,2,3]
a.append(4)

In [73]:
a ##a자체가 변화함

[1, 2, 3, 4]

`a.append(4)` :  `a`에 4를 append하라 -> `a`가 변함

`a+[4]`: `a`와 4를 연산하라

### 메소드 (리스트 자료형에 특화된 특수한 함수들)

**(append)**

In [77]:
a=[1,2,3,4]
a.append?

Signature: a.append(object, /)
Docstring: Append object to the end of the list.
Type:      builtin_function_or_method


In [78]:
a.append(5)
a

[1, 2, 3, 4, 5]

**(clear)**

In [79]:
a.clear?

Signature: a.clear()
Docstring: Remove all items from list.
Type:      builtin_function_or_method


In [80]:
a.clear()
a

[]

**(count)**

In [81]:
a=[1,1,1,1,2,3,2,3,4,3,4,4]
a.count?

Signature: a.count(value, /)
Docstring: Return number of occurrences of value.
Type:      builtin_function_or_method


In [82]:
a.count(1)

4

In [83]:
a.count(2)

2

In [84]:
a.count(3)

3

In [85]:
a.count(4)

3

**(extend)**

In [94]:
a=[1,2,3,4]
b=[-1,-2,-3,-4]

In [95]:
a.extend(b) #extend는 원소들이 자체적으로 추가
a

[1, 2, 3, 4, -1, -2, -3, -4]

In [96]:
a.append(b) #append는 b의 형태변환없이 그 자체가 추가
a

[1, 2, 3, 4, -1, -2, -3, -4, [-1, -2, -3, -4]]

**(index)**

In [97]:
a=[11,22,True,'a',22,'a']
a.index?

Signature: a.index(value, start=0, stop=9223372036854775807, /)
Docstring:
Return first index of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [98]:
a.index(11)

0

In [99]:
a.index(22)

1

In [100]:
a.index('a')

3

**(insert)**

In [101]:
a=[1,2,3]
a.insert?

Signature: a.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method


In [102]:
a.insert(1,77)
a

[1, 77, 2, 3]

**(pop)**

In [104]:
a=['a',1,2,'b']
a.pop?

Signature: a.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method


In [105]:
a.pop()

'b'

In [106]:
a

['a', 1, 2]

In [107]:
a.pop(0)

'a'

In [108]:
a

[1, 2]

**(remove)**

In [109]:
a=['a',1,2,'b']
a.remove?

Signature: a.remove(value, /)
Docstring:
Remove first occurrence of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [110]:
a.remove('b')

In [111]:
a

['a', 1, 2]

**(reverse)**

In [114]:
a=[1,2,3,4]
a.reverse?

Signature: a.reverse()
Docstring: Reverse *IN PLACE*.
Type:      builtin_function_or_method


In [115]:
a.reverse()
a

[4, 3, 2, 1]

**(sort)**

In [116]:
a=[1,3,2,4]
a.sort?

Signature: a.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method


In [117]:
a.sort()
a

[1, 2, 3, 4]

### 중첩리스트

In [118]:
A=[[1,2,3],[4,5,6],[7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

A는 매트릭스 형태라고 이해할 수 있다.

A에서 (2,1)의 원소 =4 를 뽑고 싶다

In [119]:
A[1,0]

TypeError: list indices must be integers or slices, not tuple

In [120]:
A[1][0]

4

`-` 매트릭스는 아니지만, 매트릭스 같음!
- 1차원 배열을 다차원 배열로 확장할 수 있는 기본 아이디어를 제공함

#### 리스트 컴프리헨션 ($\star\star\star\$)

`-` `for`문 예비학습

프로그램안에서 반복해서 무언가를 하고 싶을 경우 $\to\$ for

In [121]:
for i in [0,1,2,3]: ## 반복실행계획
    print(i) ## 반복실행할내용, 탭을이용해 들여쓰기

0
1
2
3


`-` 예제 : $2^0,2^1,2^2,2^3$ 을 원소로 가지는 리스트 생성

(풀이1) 직접입력

In [123]:
x=[2**0,2**1,2**2,2**3]
x

[1, 2, 4, 8]

(풀이2) for문을 이용

In [124]:
x=[]
for i in [0,1,2,3]:
    x.append(2**i)

In [125]:
x

[1, 2, 4, 8]

(풀이3) for문을 이용

In [126]:
x=[]
for i in [0,1,2,3]:
    x+=[2**i]

In [127]:
x

[1, 2, 4, 8]

(풀이4) 리스트컴프리헨션을 이용

In [128]:
x=[2**i for i in [0,1,2,3]]
x

[1, 2, 4, 8]

`-` 리스트컴프리헨션의 문법 암기방법
- 집합에서 조건제시법을 연상

`-` 리스트컴프리헨션이란?
- 리스트를 매우 효율적으로 만드는 테크닉
- for문에 비해 좋은 점: (1) 코드가 간결 (2) 빠름

`-` 예제: 리스트컴프리헨션을 이용해 통계1,통계2, ....., 수학4,수학5를 만들기

(풀이)

In [129]:
[x+y for x in ['stat','math'] for y in '12345']

['stat1',
 'stat2',
 'stat3',
 'stat4',
 'stat5',
 'math1',
 'math2',
 'math3',
 'math4',
 'math5']

- $\{xy : x \in \{stat,math\}, y \in \{1,2,3,4,5\} \}$ 

`-` x에 무엇이 들어 있을까?? / 전역변수, 지역변수/

(경우1)

In [130]:
x=1
lst=[]
for x in 'jbnu':
    lst=lst+[x]
lst

['j', 'b', 'n', 'u']

In [132]:
x #for문에서 반복되고 마지막 원소인 u가 들어가 있음.

'u'

(경우2)

In [134]:
x=1
lst =[x for x in 'jbnu']
lst

['j', 'b', 'n', 'u']

In [135]:
x

1

`-` 예비학습 : range()

In [136]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [137]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [138]:
['X'+str(i) for i in range(1,10)]

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9']